export const BASIC_CONFIGS = {
  APP_NAME: import.meta.env.VITE_APP_NAME,
  APP_SERIES_NAME: import.meta.env.VITE_APP_SERIES_NAME,
  APP_DASHBOARD_NAME: import.meta.env.VITE_APP_DASHBOARD_NAME,
  APP_SERVER_NAME: import.meta.env.VITE_APP_SERVER_NAME,

  IS_PRODUCTION: import.meta.env.MODE === "production",
  APP_DASHBOARD_USE_MOCK_DATA: import.meta.env.VITE_APP_DASHBOARD_USE_MOCK_DATA,

  APP_DASHBOARD_SERVER_PORT: import.meta.env.VITE_APP_DASHBOARD_SERVER_PORT,
  VITE_APP_DASHBOARD_DOMAIN: import.meta.env.VITE_APP_DASHBOARD_DOMAIN,
  VITE_APP_SERVER_DOMAIN: import.meta.env.VITE_APP_SERVER_DOMAIN,
};
