# Generated by Django 4.2.16 on 2025-06-19 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="( UUID )",
                primary_key=True,
                serialize=False,
                verbose_name="User ID",
            ),
        ),
    ]
